# 设置 XDG 配置目录（如果未定义则使用默认值）
: "${XDG_CONFIG_HOME:=$HOME/.config}"
SHELL_CONFIG_DIR="$XDG_CONFIG_HOME/shell"

# 载入 shell 通用配置（env, alias, fun）
shopt -s nullglob
for f in "$SHELL_CONFIG_DIR"/*.env; do source "$f"; done
for f in "$SHELL_CONFIG_DIR"/*.alias; do source "$f"; done
for f in "$SHELL_CONFIG_DIR"/*.fun; do source "$f"; done
shopt -u nullglob
