# Enable Powerlevel10k instant prompt. Should stay close to the top of ~/.zshrc.
# Initialization code that may require console input (password prompts, [y/n]
# confirmations, etc.) must go above this block; everything else may go below.
if [[ -r "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh" ]]; then
  source "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh"
fi

# ~/.zshrc
source /usr/share/zsh/plugins/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh
source /usr/share/zsh/plugins/zsh-autosuggestions/zsh-autosuggestions.zsh
source /usr/share/zsh/plugins/powerlevel10k/powerlevel10k.zsh-theme

SHELL_CONFIG_DIR="$XDG_CONFIG_HOME/shell"
# 加载 shell 通用配置（alias, env, fun）
for f in "$SHELL_CONFIG_DIR"/*.env(N);   do source "$f"; done
for f in "$SHELL_CONFIG_DIR"/*.alias(N); do source "$f"; done
for f in "$SHELL_CONFIG_DIR"/*.fun(N);   do source "$f"; done

# To customize prompt, run `p10k configure` or edit ~/.p10k.zsh.
[[ ! -f ~/.p10k.zsh ]] || source ~/.p10k.zsh
